version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: oxefood
       POSTGRES_DB: oxefood
     ports:
       - 8081:3000
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
